import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog preview card",
  description: "Blog preview card generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} flex flex-col min-h-screen bg-yellow-400`}>
      <main className="flex-grow flex items-center justify-center p-8">
        {children}
      </main>
      <footer className="text-center p-1 text-xs">
        Challenge by <a href="https://www.frontendmentor.io/challenges/blog-preview-card-ckPaj01IcS" target="_blank" style={{color:"blue"}}>Frontend Mentor</a>. 
        Coded by <a href="https://github.com/hiralinda/blog-preview-card-component" style={{color:"blue"}}>Hiralinda</a>.
      </footer>
    </body>
  </html>
  );
}
